### ISSUE TITLE
No Issue I want to thank you so so much for this. I just have to get this approved by legal and get all my developers to install this

### ISSUE THREAD

**Issue by sfransen** [neonichu/FixCode#1]
No Issue I want to thank you so so much for this. I just have to get this approved by legal and get all my developers to install this

 I am so so tired of the fix it button it creates nothing but trouble for me at work .
 Created certs and AppID and other things.
 I will make changes to support out internal process.  Thank you so so much for figuring this out.

Steven Fransen

**Comment by KrauseFx** [comment]
I'm so happy you find it useful @sfransen. In case you use `fastlane`, you can even automatically install it on all machines (see [fastlane installation](https://github.com/fastlane/FixCode#using-fastlane)).

Keep me up to date and let me know once you roll this out to all your developer's machines :+1:

**Comment by neonichu** [comment]
![](http://www.reactiongifs.com/r/flwr.gif)
