### ISSUE TITLE
Fix issue button showing up in Xcode 7.3

### ISSUE THREAD

**Issue by mdio** [neonichu/FixCode#14]
I installed FixCode 0.3.0 in Xcode 7.3 (7D175) via fastlane install_xcode_plugin and also tried via Alcatraz (remove, install again) but I'm still getting this: 
![fix-issue-problem](https://cloud.githubusercontent.com/assets/8616698/14357589/94293422-fce9-11e5-9e93-6af24d9ee227.png)

I would assume that this is the kind of stuff FixCode should take care of.

Maybe also helpful: When I started Xcode after installing Alcatraz I was asked if I want to enable that plugin but I was never asked for FixCode.
But I can confirm the existance of /Users/myuser/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin
It also has the same permissions as Alcatraz.xcplugin.

**Comment by mdio** [comment]
I can confirm that it works now.
Thanks for the quick fix!

**Comment by KrauseFx** [comment]
@neonichu for president
