### ISSUE TITLE
disable fix issue button on capabilities

### ISSUE THREAD

**Issue by hjanuschka** [neonichu/FixCode#15]
we recently had problems as one of us hit the "fix issues" on the capabilities screen.
any chance we can disable this too - or atleast have a confirmation dialog?

this is the one i mean.
![bildschirmfoto 2016-04-22 um 10 53 16](https://cloud.githubusercontent.com/assets/2891702/14736746/c3a3acc4-0878-11e6-965d-39719e661792.png)

as this seems to update the appId on itc, wich invalidates provisioning profiles.

**Comment by neonichu** [comment]
Didn't even know this one existed :) I'll look into disabling it as well.

**Comment by neonichu** [comment]
<img width="367" alt="screen shot 2016-04-22 at 15 22 24" src="https://cloud.githubusercontent.com/assets/118992/14742791/41607d5c-089e-11e6-8eb6-654312612c3f.png">

**Comment by neonichu** [comment]
Love the class name `IDEFlightCheckListView` :)

**Comment by hjanuschka** [comment]
many thx
