### ISSUE TITLE
Fix the Fix Issue button when connecting a device

### ISSUE THREAD

**Issue by KrauseFx** [neonichu/FixCode#2]
It seems like the title of the Fix Issue button inside the Xcode project settings gets overwritten when connecting a new device. We should find the event that triggers this, as we currently only do this on `viewWillAppear`

**Comment by neonichu** [comment]
😱

**Comment by KrauseFx** [comment]
Can you reproduce the `Issue`?

**Comment by neonichu** [comment]
I couldn't reproduce it, but could you check if this branch resolves it? https://github.com/fastlane/FixCode/tree/fix-connect-device

**Comment by neonichu** [comment]
@KrauseFx :bell:

**Comment by KrauseFx** [comment]
:hamburger:

**Comment by neonichu** [comment]
@KrauseFx is that a yes? :grin:

**Comment by neonichu** [comment]
I'm assuming #11 also fixes this.
