### ISSUE TITLE
Add prefixes to vendored Objective-C symbols

### ISSUE THREAD

**Issue by Ashton-W** [neonichu/FixCode#5]
Xcode plugin class names and symbols can clash and should be prefixed, this includes any vendored libraries:

> objc[47572]: Class AspectTracker is implemented in both /Users/AshtonWilliams/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin/Contents/MacOS/FixCode and /Users/AshtonWilliams/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin/Contents/MacOS/BBUFullIssueNavigator. One of the two will be used. Which one is undefined.

I think all the Objective-C symbols in Aspects should be prefixed.

---

See neonichu/BBUDebuggerTuckAway#13

**Comment by neonichu** [comment]
Yep, they should be — was too lazy to initially do it :)

**Comment by KrauseFx** [comment]
Closing this, as sad as it makes me 😢
