### ISSUE TITLE
'fix issue' button reappears if you edit the Version number

### ISSUE THREAD

**Issue by alexkent** [neonichu/FixCode#6]
The fix issue button reappears the moment you edit text in the Version number field.
I have not clicked the button (for fear!) to see if the behaviour changes as well.

**Comment by KrauseFx** [comment]
@alexkent Don't click it if there are no emojis! :+1:

**Comment by neonichu** [comment]
The proposed fix for #2 might also fix this. I can't test this right now, because I can't get the "Fix Issue" thing to appear in the project editor :/

**Comment by neonichu** [comment]
Did anyone ever test this with the branch?

**Comment by KrauseFx** [comment]
#YOLO and merge

**Comment by neonichu** [comment]
I'm assuming #11 also fixes this.
