### ISSUE TITLE
What's the best way to tell Xcode to update its provisioning profiles after adding a new device?

### ISSUE THREAD

**Issue by Buju77** [neonichu/FixCode#7]
Hi,

I'm so glad you guys made FixCode! Thank you for that! Because recently we had the issue that someone pressed the evil "Fix Issue" button and suddenly all our certs and profiles was invalid.

But now after installing FixCode, how do we tell Xcode to update its profiles after adding a new device to the developer portal, so I can deploy on the new device immediately? Xcode is using the `iOS Team Provisioning Profile: * (Managed by Xcode)` for that right? Or is it using `iOS Team Provisioning Profile: <bundleId> (Manged by Xcode)`?

Previously there was a refresh button in Xcode, but that one was replaced a crappy "Download All" which does nothing at all.

Current workaround we found was to remove the account and re-add it again, so Xcode will download the updated correct profiles again.

**Comment by sfransen** [comment]
I have Cupertino code to do that never got spaceship or fastlane to work for downloading provisions
I have too many and the code just doesn't work right after x many

**Comment by neonichu** [comment]
I'm recommending following https://codesigning.guide for the whole process and just asking @KrauseFx if there's still issues 😎
